name: "🐛 Bug Report"
description: Report a bug or unexpected behavior in SwapSmith
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting a bug! 🐛
        
        Please fill out the sections below to help us understand and fix the issue quickly.
        
        **Before submitting:**
        - Search existing issues to avoid duplicates
        - Make sure you're using the latest version
        - Check if the issue occurs in a clean environment

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing in detail
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happens
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of SwapSmith is affected?
      options:
        - Frontend (Web UI)
        - Bot (Telegram)
        - Backend/API
        - Database
        - Wallet Integration
        - Voice Input
        - Swap Functionality
        - Portfolio Management
        - DCA (Dollar Cost Averaging)
        - Limit Orders
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (App crashes or data loss)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue or cosmetic)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Browser: [e.g., Chrome 120, Firefox 121, Safari 17]
        - Node Version: [e.g., 20.10.0]
        - SwapSmith Version: [e.g., 1.0.0]
      value: |
        - OS: 
        - Browser: 
        - Node Version: 
        - SwapSmith Version: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Screenshots
      description: Add any relevant error messages, logs, or screenshots
      placeholder: |
        Paste error logs here or drag and drop screenshots
        
        ```
        Error message here
        ```
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: |
        - Does this happen consistently or intermittently?
        - Did this work before? If so, when did it break?
        - Any workarounds you've found?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all required information above
          required: true
        - label: I am using the latest version of SwapSmith
          required: false
        - label: I can reproduce this issue consistently
          required: false
